### PR TITLE
Replace cookie-based authentication with basic authentication, add inline help

### PR DESCRIPTION
**Pull request by unobe**
@kennylevinsen , thank you for this repo! I'm now using jirafs to interface with the JIRA deployment at my day job. This pull request is to handle JIRA deprecation and removal of cookie-based authentication support, replacing it with basic authentication. I've updated the documentation accordingly. Unrelated, but I had to change time.Time(w.Started).String() to time.Time(*w.Started).String() in jira.go to even build building with the latest go-jira.

### CODE REVIEW

**Comment by kennylevinsen** [comment]
Aha, it's always fun to discover that your old for-fun projects end up being of use to someone, enough so for them to contribute changes. :)

A few things:
1. Indention seem a bit whack. Could I get you to run gofmt on your commits?
2. Could we still list Mac9P in the readme? 9pfuse was quite quirky IIRC.
3. Could you combine your update readme and fix typo commits?

**Comment by unobe** [comment]
1. For sure, the indentation is weird--I realized that after and then did s/    /\t/g. I'm not a go programmer really (altho' I'm interested), so much of this is admittedly hackish.
2. Will do!
3. Yep

**Comment by unobe** [comment]
I've pushed the commits.

**Comment by kennylevinsen** [comment]
Thank you for your contribution!

I ended up squashing everything, due to the large amount of commits. That, and being too lazy to reorganize it myself. :)

In the future, please look into performing what is called an "interactive rebase", which allows you to combine fix-up commits with their initial commit, as well as reorganize your history as you see fit. This particular PR, for example, contained what would logically be 2 commits: Authentication change and inline help.

It's no biggie for this tiny project, but a pretty git history is always nice!

**Pull request merged**
